spring:
  application:
    name: POST-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/postdb
    username: root
    password: Hari@141101

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

  eureka:
    instance:
      prefer-ip-address: true
      client:
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka



